version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: deepfaked
    volumes:
      - /data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
  server:
    container_name: deepfaked-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "8000:8000"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  client:
    container_name: deepfaked-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      - server
